name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.1.3-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN : ${{ secrets.CLA_ACCESS_TOKEN }}
        with:
          path-to-signatures: 'signatures/nvrhi.json'
          path-to-document: 'https://github.com/NVIDIAGameWorks/nvrhi/blob/main/CLA.txt'
          branch: 'nvrhi'
          allowlist: nobody
          lock-pullrequest-aftermerge: true
          remote-organization-name: NVIDIAGameWorks
          remote-repository-name: CLAs
